# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c41fb94812c7126b2bfccda4219bf469ecedb84382aebcaf2ba06499352fe1b91710545769277a5fbbf95e3353571692c320b9b68fec2da85b3a0fa8938019

test:
  secret_key_base: a6316b861d60cf2816e06ae5b187da0e2e62d8c9cb36f1da752677d102f71881ef3c8b0cad2f14dc42299d88ed1c04e8f3f1147c13b8d2f1b50fb942f7db94fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
